-- MySQL Script generated by MySQL Workbench
-- Tue Aug 13 15:35:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cc_bot_db_dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cc_bot_db_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cc_bot_db_dev` DEFAULT CHARACTER SET latin1 ;
USE `cc_bot_db_dev` ;

-- -----------------------------------------------------
-- Table `cc_bot_db_dev`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc_bot_db_dev`.`course` (
  `subject` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'use the abreviated form(ex: CSCI, ABOD)',
  `number` MEDIUMINT(250) NOT NULL,
  `name` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `goal` SET('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15') NULL DEFAULT NULL,
  `url` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`subject`, `number`))
ENGINE = MariaDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cc_bot_db_dev`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc_bot_db_dev`.`events` (
  `event_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `url` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`event_id`),
  UNIQUE INDEX `event_id_UNIQUE` (`event_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cc_bot_db_dev`.`faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc_bot_db_dev`.`faculty` (
  `faculty_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `lastname` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `location` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `department` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `title` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `phone` BIGINT(10) NULL DEFAULT NULL,
  `email` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`faculty_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1094
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cc_bot_db_dev`.`pathway`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc_bot_db_dev`.`pathway` (
  `pathway_id` INT(10) UNSIGNED NOT NULL,
  `name` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `url` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `img_url` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`pathway_id`),
  UNIQUE INDEX `idpathway_UNIQUE` (`pathway_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cc_bot_db_dev`.`pathway_has_advisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc_bot_db_dev`.`pathway_has_advisor` (
  `pathway_id` INT(10) UNSIGNED NOT NULL,
  `faculty_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`pathway_id`, `faculty_id`),
  INDEX `fk_pathway_has_advisor_pathway1_idx` (`pathway_id` ASC) VISIBLE,
  INDEX `fk_pathway_has_advisor_faculty1_idx` (`faculty_id` ASC) VISIBLE,
  CONSTRAINT `fk_pathway_has_advisor_faculty1`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `cc_bot_db_dev`.`faculty` (`faculty_id`),
  CONSTRAINT `fk_pathway_has_advisor_pathway1`
    FOREIGN KEY (`pathway_id`)
    REFERENCES `cc_bot_db_dev`.`pathway` (`pathway_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cc_bot_db_dev`.`program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc_bot_db_dev`.`program` (
  `program_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `pathway_id` INT(10) UNSIGNED NOT NULL,
  `description` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `url` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`program_id`),
  UNIQUE INDEX `idprogram_UNIQUE` (`program_id` ASC) VISIBLE,
  INDEX `fk_program_pathway1_idx` (`pathway_id` ASC) VISIBLE,
  CONSTRAINT `fk_program_pathway`
    FOREIGN KEY (`pathway_id`)
    REFERENCES `cc_bot_db_dev`.`pathway` (`pathway_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 88
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cc_bot_db_dev`.`requests_legal_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc_bot_db_dev`.`requests_legal_record` (
  `userid` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `cyphertext` TEXT NOT NULL,
  `cypherkey` TEXT NOT NULL,
  `iv` TEXT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cc_bot_db_dev`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc_bot_db_dev`.`section` (
  `section_id` INT(255) UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` TINYINT(250) UNSIGNED NOT NULL,
  `term` ENUM('j-term', 'spring', 'summer', 'fall') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `resident_tuition` DECIMAL(6,2) NULL DEFAULT NULL,
  `nonresident_tuition` DECIMAL(6,2) NULL DEFAULT NULL,
  `fees` DECIMAL(6,2) NULL DEFAULT NULL,
  `course_subject` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `course_number` MEDIUMINT(250) NOT NULL,
  `year` YEAR(4) NOT NULL,
  `description` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `url` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `credits` SMALLINT(3) UNSIGNED NULL DEFAULT NULL,
  `campus` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `offered_through` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `location` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`section_id`),
  UNIQUE INDEX `idsection_UNIQUE` (`section_id` ASC) VISIBLE,
  INDEX `fk_section_course_idx` (`course_subject` ASC, `course_number` ASC) INVISIBLE,
  CONSTRAINT `fk_section_course`
    FOREIGN KEY (`course_subject` , `course_number`)
    REFERENCES `cc_bot_db_dev`.`course` (`subject` , `number`))
ENGINE = InnoDB
AUTO_INCREMENT = 6194
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cc_bot_db_dev`.`study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc_bot_db_dev`.`study` (
  `study_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` ENUM('degree', 'certificate', 'diploma', 'NA') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `name` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `program_id` INT(10) UNSIGNED NOT NULL,
  `description` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `url` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `credit` INT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`study_id`),
  UNIQUE INDEX `idstudy_UNIQUE` (`study_id` ASC) VISIBLE,
  INDEX `fk_study_program1_idx` (`program_id` ASC) VISIBLE,
  CONSTRAINT `fk_study_program1`
    FOREIGN KEY (`program_id`)
    REFERENCES `cc_bot_db_dev`.`program` (`program_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 185
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
KEY_BLOCK_SIZE = 16;


-- -----------------------------------------------------
-- Table `cc_bot_db_dev`.`study_has_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc_bot_db_dev`.`study_has_course` (
  `study_id` INT(10) UNSIGNED NOT NULL,
  `course_subject` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `course_number` MEDIUMINT(250) NOT NULL,
  PRIMARY KEY (`study_id`, `course_subject`, `course_number`),
  INDEX `fk_study_has_course_study1_idx` (`study_id` ASC) VISIBLE,
  INDEX `fk_study_has_course_course_idx` (`course_subject` ASC, `course_number` ASC) INVISIBLE,
  CONSTRAINT `fk_study_has_course_course`
    FOREIGN KEY (`course_subject` , `course_number`)
    REFERENCES `cc_bot_db_dev`.`course` (`subject` , `number`),
  CONSTRAINT `fk_study_has_course_study1`
    FOREIGN KEY (`study_id`)
    REFERENCES `cc_bot_db_dev`.`study` (`study_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cc_bot_db_dev`.`study_has_faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc_bot_db_dev`.`study_has_faculty` (
  `study_id` INT(10) UNSIGNED NOT NULL,
  `faculty_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`study_id`, `faculty_id`),
  INDEX `fk_study_has_faculty_faculty1_idx` (`faculty_id` ASC) VISIBLE,
  INDEX `fk_study_has_faculty_study1_idx` (`study_id` ASC) VISIBLE,
  CONSTRAINT `fk_study_has_faculty_faculty1`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `cc_bot_db_dev`.`faculty` (`faculty_id`),
  CONSTRAINT `fk_study_has_faculty_study1`
    FOREIGN KEY (`study_id`)
    REFERENCES `cc_bot_db_dev`.`study` (`study_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `cc_bot_db_dev`.`subject_abrv_to_full`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc_bot_db_dev`.`subject_abrv_to_full` (
  `abrev` VARCHAR(45) NOT NULL,
  `full` TEXT NOT NULL,
  PRIMARY KEY (`abrev`),
  UNIQUE INDEX `abrev_UNIQUE` (`abrev` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cc_bot_db_dev`.`times`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cc_bot_db_dev`.`times` (
  `times_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `startdate` DATE NOT NULL,
  `enddate` DATE NOT NULL,
  `starttime` TIME NULL DEFAULT NULL,
  `endtime` TIME NULL DEFAULT NULL,
  `section_id` INT(255) UNSIGNED NOT NULL,
  `days` SET('sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday') NULL DEFAULT NULL,
  `faculty_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`times_id`),
  UNIQUE INDEX `idtimes_UNIQUE` (`times_id` ASC) VISIBLE,
  INDEX `fk_times_section1_idx` (`section_id` ASC) VISIBLE,
  INDEX `fk_times_faculty_idx` (`faculty_id` ASC) VISIBLE,
  CONSTRAINT `fk_times_faculty`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `cc_bot_db_dev`.`faculty` (`faculty_id`),
  CONSTRAINT `fk_times_section1`
    FOREIGN KEY (`section_id`)
    REFERENCES `cc_bot_db_dev`.`section` (`section_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7476
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
